language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
env:
  - rails=3.1
  - rails=3.2
  - rails=4.0
  - rails=4.1
  - table_name_prefix=h_
  - table_name_suffix=_h
gemfile:
  - Gemfile
  - gemfiles/Gemfile.mongoid2.rb
  - gemfiles/Gemfile.mongoid3.rb
  - gemfiles/Gemfile.mongoid4.rb
  - gemfiles/Gemfile.mongo_mapper.rb
services:
  - mongodb
matrix:
  exclude:
    - gemfile: gemfiles/Gemfile.mongoid4.rb
      env: rails=3.1
    - gemfile: gemfiles/Gemfile.mongoid4.rb
      env: rails=3.2
